#!/usr/bin/env bash

abspath="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
bin_dir=`dirname "$abspath"`
root_dir=`dirname $bin_dir`

source $bin_dir/aws

cd "$root_dir"

check_env
create_lambda_services
deploy_bundle
