#!/usr/bin/env bash

abspath="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
bin_dir=`dirname "$abspath"`
root_dir=`dirname $bin_dir`

source $bin_dir/aws

cd "$root_dir"

init_env prod

build_bundle
create_lambda_services
deploy_bundle

curl -d "channel_name=pbp&user_name=Brian&text=1d20%20%2B%204" https://to8vpiu5b7.execute-api.us-east-1.amazonaws.com/prod/slackroll_roll
