#!/usr/bin/env bash

abspath="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
bin_dir=`dirname "$abspath"`

source $bin_dir/aws

cd $bin_dir/..

init_env dev

# The current directory is included in PYTHONPATH on OS X, but not Linux
export PYTHONPATH=.

if [[ -x `which entr` ]]; then
  ls slackroll/*.py test/*.py | entr py.test --color=yes test
else
  py.test --color=yes test
fi
